compare:
  # Output dir, absolute or relative to current dir
  output: /shots
  # Scripts dir, absolute or relative to current dir
  scripts: /scripts
  # Path to binary compare from ImageMagick package, in some cases /usr/local/bin/compare
  compare_binary: /usr/bin/compare
  keep_identical_diff: False
  # Default screenshot size
  # Height is limited to 14000 px due to libpng memory limitation issue
  # https://stackoverflow.com/questions/25490332/lodepng-crashes-when-encoding-png-files-with-size-greater-than-15000-15000-pix
  screen_size:
    - "1300x3000"
  # Default screenshot timeout
  screenshot_timeout: 1000
history:
  screen_size:
    - "1280x1300"
  output: history

# Links to websites (test and prod). Prod URL is also used for history
url:
  prod: https://climate.copernicus.eu
  test: https://www.google.com/

# Pages to be compared
links:
  homepage: /
  node_479_en: /1st-artificial-intelligence-copernicus-workshop
