compare:
  output: /home/cristiroma/Work/iucn-whp/test.visual.3/shots
  compare_bin: /usr/bin/compare
  url:
    prod: https://www.worldheritageoutlook.iucn.org
    test: https://iucn-who.edw.ro
  links:
    homepage: /
    site_191: /explore-sites/wdpaid/191
    site_197: /explore-sites/wdpaid/197

history:
  output: history
  url:    https://www.worldheritageoutlook.iucn.org
  links:
    homepage: /
    site_191: /explore-sites/wdpaid/191
    site_197: /explore-sites/wdpaid/197
    site_2004: /explore-sites/wdpaid/2004
    site_2005: /explore-sites/wdpaid/2005
    site_2006: /explore-sites/wdpaid/2006
    site_2007: /explore-sites/wdpaid/2007
    site_2008: /explore-sites/wdpaid/2008
    site_2010: /explore-sites/wdpaid/2010
    site_2011: /explore-sites/wdpaid/2011
    site_2012: /explore-sites/wdpaid/2012
    site_2013: /explore-sites/wdpaid/2013
    site_2015: /explore-sites/wdpaid/2015
    site_2016: /explore-sites/wdpaid/2016
    site_2017: /explore-sites/wdpaid/2017
    site_2018: /explore-sites/wdpaid/2018
    site_2554: /explore-sites/wdpaid/2554
    site_2570: /explore-sites/wdpaid/2570
    site_2571: /explore-sites/wdpaid/2571
    site_2572: /explore-sites/wdpaid/2572
    site_2573: /explore-sites/wdpaid/2573
    site_2574: /explore-sites/wdpaid/2574
    site_2575: /explore-sites/wdpaid/2575
    site_2577: /explore-sites/wdpaid/2577
    site_2578: /explore-sites/wdpaid/2578
    site_2579: /explore-sites/wdpaid/2579
    site_2580: /explore-sites/wdpaid/2580
    site_4322: /explore-sites/wdpaid/4322
    site_4325: /explore-sites/wdpaid/4325
    site_4326: /explore-sites/wdpaid/4326
    site_4327: /explore-sites/wdpaid/4327
    site_4328: /explore-sites/wdpaid/4328
    site_4999: /explore-sites/wdpaid/4999
    site_5000: /explore-sites/wdpaid/5000
    site_5001: /explore-sites/wdpaid/5001
    site_5002: /explore-sites/wdpaid/5002
    site_5003: /explore-sites/wdpaid/5003
    site_5004: /explore-sites/wdpaid/5004
    site_5005: /explore-sites/wdpaid/5005
    site_9545: /explore-sites/wdpaid/9545
    site_9612: /explore-sites/wdpaid/9612
    site_9613: /explore-sites/wdpaid/9613
    site_9614: /explore-sites/wdpaid/9614
    site_9617: /explore-sites/wdpaid/9617
    site_9623: /explore-sites/wdpaid/9623
    site_9628: /explore-sites/wdpaid/9628
    site_9632: /explore-sites/wdpaid/9632
    site_10744: /explore-sites/wdpaid/10744
    site_10745: /explore-sites/wdpaid/10745
    site_10746: /explore-sites/wdpaid/10746
    site_10747: /explore-sites/wdpaid/10747
    site_10901: /explore-sites/wdpaid/10901
    site_10902: /explore-sites/wdpaid/10902
    site_10903: /explore-sites/wdpaid/10903
    site_10904: /explore-sites/wdpaid/10904
    site_10905: /explore-sites/wdpaid/10905
    site_10906: /explore-sites/wdpaid/10906
    site_10907: /explore-sites/wdpaid/10907
    site_10908: /explore-sites/wdpaid/10908
    site_12202: /explore-sites/wdpaid/12202
    site_12203: /explore-sites/wdpaid/12203
    site_12206: /explore-sites/wdpaid/12206
    site_12207: /explore-sites/wdpaid/12207
    site_12209: /explore-sites/wdpaid/12209
    site_12896: /explore-sites/wdpaid/12896
    site_14177: /explore-sites/wdpaid/14177
    site_16791: /explore-sites/wdpaid/16791
    site_16792: /explore-sites/wdpaid/16792
    site_16793: /explore-sites/wdpaid/16793
    site_17050: /explore-sites/wdpaid/17050
    site_17757: /explore-sites/wdpaid/17757
    site_17758: /explore-sites/wdpaid/17758
    site_17759: /explore-sites/wdpaid/17759
    site_17760: /explore-sites/wdpaid/17760
    site_17761: /explore-sites/wdpaid/17761
    site_18337: /explore-sites/wdpaid/18337
    site_18862: /explore-sites/wdpaid/18862
    site_18863: /explore-sites/wdpaid/18863
    site_20062: /explore-sites/wdpaid/20062
    site_20171: /explore-sites/wdpaid/20171
    site_20388: /explore-sites/wdpaid/20388
    site_20399: /explore-sites/wdpaid/20399
    site_26649: /explore-sites/wdpaid/26649
    site_26651: /explore-sites/wdpaid/26651
    site_26652: /explore-sites/wdpaid/26652
    site_26653: /explore-sites/wdpaid/26653
    site_26654: /explore-sites/wdpaid/26654
    site_26689: /explore-sites/wdpaid/26689
    site_61604: /explore-sites/wdpaid/61604
    site_61608: /explore-sites/wdpaid/61608
    site_61609: /explore-sites/wdpaid/61609
    site_61610: /explore-sites/wdpaid/61610
    site_61611: /explore-sites/wdpaid/61611
    site_61612: /explore-sites/wdpaid/61612
    site_67724: /explore-sites/wdpaid/67724
    site_67725: /explore-sites/wdpaid/67725
    site_67726: /explore-sites/wdpaid/67726
    site_67727: /explore-sites/wdpaid/67727
    site_67728: /explore-sites/wdpaid/67728
    site_67729: /explore-sites/wdpaid/67729
    site_67730: /explore-sites/wdpaid/67730
    site_67731: /explore-sites/wdpaid/67731
    site_67732: /explore-sites/wdpaid/67732
    site_67733: /explore-sites/wdpaid/67733
    site_68915: /explore-sites/wdpaid/68915
    site_68916: /explore-sites/wdpaid/68916
    site_68917: /explore-sites/wdpaid/68917
    site_68918: /explore-sites/wdpaid/68918
    site_93290: /explore-sites/wdpaid/93290
    site_93291: /explore-sites/wdpaid/93291
    site_93292: /explore-sites/wdpaid/93292
    site_93294: /explore-sites/wdpaid/93294
    site_93295: /explore-sites/wdpaid/93295
    site_93767: /explore-sites/wdpaid/93767
    site_124383: /explore-sites/wdpaid/124383
    site_124384: /explore-sites/wdpaid/124384
    site_124385: /explore-sites/wdpaid/124385
    site_124386: /explore-sites/wdpaid/124386
    site_124387: /explore-sites/wdpaid/124387
    site_124388: /explore-sites/wdpaid/124388
    site_124389: /explore-sites/wdpaid/124389
    site_145576: /explore-sites/wdpaid/145576
    site_145579: /explore-sites/wdpaid/145579
    site_145580: /explore-sites/wdpaid/145580
    site_145582: /explore-sites/wdpaid/145582
    site_145583: /explore-sites/wdpaid/145583
    site_145585: /explore-sites/wdpaid/145585
    site_145586: /explore-sites/wdpaid/145586
    site_145590: /explore-sites/wdpaid/145590
    site_168239: /explore-sites/wdpaid/168239
    site_168241: /explore-sites/wdpaid/168241
    site_168242: /explore-sites/wdpaid/168242
    site_198291: /explore-sites/wdpaid/198291
    site_198292: /explore-sites/wdpaid/198292
    site_198293: /explore-sites/wdpaid/198293
    site_198294: /explore-sites/wdpaid/198294
    site_198295: /explore-sites/wdpaid/198295
    site_198296: /explore-sites/wdpaid/198296
    site_198297: /explore-sites/wdpaid/198297
    site_198298: /explore-sites/wdpaid/198298
    site_198299: /explore-sites/wdpaid/198299
    site_198300: /explore-sites/wdpaid/198300
    site_198301: /explore-sites/wdpaid/198301
    site_198302: /explore-sites/wdpaid/198302
    site_198303: /explore-sites/wdpaid/198303
    site_220291: /explore-sites/wdpaid/220291
    site_220292: /explore-sites/wdpaid/220292
    site_220293: /explore-sites/wdpaid/220293
    site_220294: /explore-sites/wdpaid/220294
    site_220295: /explore-sites/wdpaid/220295
    site_220296: /explore-sites/wdpaid/220296
    site_220297: /explore-sites/wdpaid/220297
    site_220298: /explore-sites/wdpaid/220298
    site_478637: /explore-sites/wdpaid/478637
    site_478638: /explore-sites/wdpaid/478638
    site_478640: /explore-sites/wdpaid/478640
    site_478641: /explore-sites/wdpaid/478641
    site_478642: /explore-sites/wdpaid/478642
    site_900006: /explore-sites/wdpaid/900006
    site_900008: /explore-sites/wdpaid/900008
    site_900010: /explore-sites/wdpaid/900010
    site_900628: /explore-sites/wdpaid/900628
    site_900629: /explore-sites/wdpaid/900629
    site_900630: /explore-sites/wdpaid/900630
    site_900631: /explore-sites/wdpaid/900631
    site_900632: /explore-sites/wdpaid/900632
    site_900633: /explore-sites/wdpaid/900633
    site_900878: /explore-sites/wdpaid/900878
    site_900879: /explore-sites/wdpaid/900879
    site_900880: /explore-sites/wdpaid/900880
    site_900881: /explore-sites/wdpaid/900881
    site_900883: /explore-sites/wdpaid/900883
    site_900889: /explore-sites/wdpaid/900889
    site_902335: /explore-sites/wdpaid/902335
    site_902347: /explore-sites/wdpaid/902347
    site_902356: /explore-sites/wdpaid/902356
    site_902367: /explore-sites/wdpaid/902367
    site_902368: /explore-sites/wdpaid/902368
    site_902373: /explore-sites/wdpaid/902373
    site_902479: /explore-sites/wdpaid/902479
    site_902480: /explore-sites/wdpaid/902480
    site_902481: /explore-sites/wdpaid/902481
    site_902482: /explore-sites/wdpaid/902482
    site_902483: /explore-sites/wdpaid/902483
    site_902487: /explore-sites/wdpaid/902487
    site_902489: /explore-sites/wdpaid/902489
    site_902899: /explore-sites/wdpaid/902899
    site_902902: /explore-sites/wdpaid/902902
    site_903062: /explore-sites/wdpaid/903062
    site_903129: /explore-sites/wdpaid/903129
    site_903130: /explore-sites/wdpaid/903130
    site_903131: /explore-sites/wdpaid/903131
    site_903132: /explore-sites/wdpaid/903132
    site_903133: /explore-sites/wdpaid/903133
    site_903134: /explore-sites/wdpaid/903134
    site_903135: /explore-sites/wdpaid/903135
    site_903136: /explore-sites/wdpaid/903136
    site_903137: /explore-sites/wdpaid/903137
    site_903138: /explore-sites/wdpaid/903138
    site_903139: /explore-sites/wdpaid/903139
    site_903140: /explore-sites/wdpaid/903140
    site_903141: /explore-sites/wdpaid/903141
    site_555512000: /explore-sites/wdpaid/555512000
    site_555512001: /explore-sites/wdpaid/555512001
    site_555512002: /explore-sites/wdpaid/555512002
    site_555512003: /explore-sites/wdpaid/555512003
    site_555512005: /explore-sites/wdpaid/555512005
    site_555512006: /explore-sites/wdpaid/555512006
    site_555542336: /explore-sites/wdpaid/555542336
    site_555542337: /explore-sites/wdpaid/555542337
    site_555542338: /explore-sites/wdpaid/555542338
    site_555542339: /explore-sites/wdpaid/555542339
    site_555547987: /explore-sites/wdpaid/555547987
    site_555547988: /explore-sites/wdpaid/555547988
    site_555547989: /explore-sites/wdpaid/555547989
    site_555547990: /explore-sites/wdpaid/555547990
    site_555547991: /explore-sites/wdpaid/555547991
    site_555547992: /explore-sites/wdpaid/555547992
    site_555556047: /explore-sites/wdpaid/555556047
    site_555556048: /explore-sites/wdpaid/555556048
    site_555556049: /explore-sites/wdpaid/555556049
    site_555556046: /explore-sites/wdpaid/555556046
    site_555556045: /explore-sites/wdpaid/555556045
    site_555577555: /explore-sites/wdpaid/555577555
    site_555577557: /explore-sites/wdpaid/555577557
    site_555577559: /explore-sites/wdpaid/555577559
    site_555577556: /explore-sites/wdpaid/555577556
    site_555577558: /explore-sites/wdpaid/555577558
    site_555577560: /explore-sites/wdpaid/555577560
    site_555555555: /explore-sites/wdpaid/555555555
    site_555622043: /explore-sites/wdpaid/555622043
    site_555622041: /explore-sites/wdpaid/555622041
    site_555622048: /explore-sites/wdpaid/555622048
    site_555622042: /explore-sites/wdpaid/555622042
    site_555622047: /explore-sites/wdpaid/555622047
    site_555622046: /explore-sites/wdpaid/555622046
    site_555622045: /explore-sites/wdpaid/555622045
    site_555622044: /explore-sites/wdpaid/555622044
    site_555622040: /explore-sites/wdpaid/555622040
    site_555624857: /explore-sites/wdpaid/555624857
    site_555624858: /explore-sites/wdpaid/555624858
    site_555624859: /explore-sites/wdpaid/555624859
