compare:
  # Output dir, absolute or relative to current dir
  output: /shots
  # Scripts dir, absolute or relative to current dir
  scripts: /scripts
  # Path to binary compare from ImageMagick package, in some cases /usr/local/bin/compare
  compare_binary: /usr/bin/compare
  keep_identical_diff: False
  # Default screenshot size
  # Height is limited to 14000 px due to libpng memory limitation issue
  # https://stackoverflow.com/questions/25490332/lodepng-crashes-when-encoding-png-files-with-size-greater-than-15000-15000-pix
  screen_size:
    - "1300x3000"
  # Default screenshot timeout
  screenshot_timeout: 1000
  # Prod and test site URLs
  url:
    prod: https://www.worldheritageoutlook.iucn.org
    test: https://iucn-who.edw.ro
  # Pages to be compared
  links:
    explore_sites: /explore-sites
    homepage:
      path: /
      screen_size:
        - "1280x1024"
    site_191:
      path: /explore-sites/wdpaid/191
      screen_size:
        - "1280x14000"
      screenshot_timeout: 2000

history:
  output: history
  url:    https://www.worldheritageoutlook.iucn.org
  links:
    homepage: /
    about: /about
    site_191: /explore-sites/wdpaid/191
